import Head from 'next/head';
import { ReactElement } from 'react';
import Layout from '../components/layout';
import { trpc } from '../utils/trpc';
import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      Test2
    </>
  );
};

const getLayout = (page: ReactElement) => {
  return <Layout>{page}</Layout>;
};

Home.getLayout = getLayout;

export default Home;

