import type { NextPage } from 'next';
import Head from 'next/head';
import { ReactElement } from 'react';
import Layout from '../components/layout';
import { trpc } from '../utils/trpc';
import { NextPageWithLayout } from './_app';

const Login: NextPageWithLayout = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      Login
    </>
  );
};

export default Login;

const getLayout = (page: ReactElement) => {
  return (
    <div>
      {page}
    </div>
  )
}

Login.getLayout = getLayout